name: BuildTools
version: '1.0.0-1.21.4'
main: dev.klayses.buildTools.BuildTools
api-version: '1.21'
load: STARTUP
authors: [ Mynny ]
description: A building utility plugin
website: discord.klayses.dev

commands:
  buildtools:
    aliases: [bt]
    description: Give building tools.

